apiVersion: batch/v1
kind: Job
metadata:
  name: job-demo
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["echo", "k8s jobs"]
      restartPolicy: Never
  backoffLimit: 4

