apiVersion: v1
kind: Pod
metadata:
  name: web-prod
  labels:
    app: web
    env: prod
spec:
  containers:
    - name: nginx
      image: nginx

---
apiVersion: v1
kind: Pod
metadata:
  name: web-dev
  labels:
    app: web
    env: dev
spec:
  containers:
    - name: nginx
      image: nginx
