apiVersion: v1
kind: Pod
metadata:
  name: pvc-mount
spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - name: pvc-vol
      mountPath: /app/pvc-volume
  volumes:
  - name: pvc-vol
    persistentVolumeClaim:
      claimName: my-pvc

