apiVersion: v1
kind: Pod
metadata:
  name: emptydir-nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    volumeMounts:
    - name: emptydir-vol
      mountPath: /var/log/nginx

  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - |
        while true; do
          echo "Listing logs..."
          ls /var/log/nginx;
          echo "Access Log:"
          cat /var/log/nginx/access.log 2>/dev/null;
          sleep 10;
        done
    volumeMounts:
    - name: emptydir-vol
      mountPath: /var/log/nginx

  volumes:
  - name: emptydir-vol
    emptyDir: {}

